# Generated by Django 5.0.4 on 2024-05-25 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_lesson_course_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Название курса'),
        ),
    ]
